### ISSUE TITLE
Method add commonds doesn't support method of class;

### ISSUE THREAD

**Issue by osolovyoff** [kroimon/Arduino-SerialCommand#12]
I want use like: sc.addCommand(&MPU::start, this); // why not ?

**Comment by dwyban** [comment]
This isn't an issue with the library.  It's a C/C++ thing.  Function pointers to instance methods doesn't really work.  There are articles on the web that explain why, but basically calling an instance method is NOT the same as calling a function.  If you want this to work then you'll want to use a static method as a static method is called basically the same way as a standard C function.
