### ISSUE TITLE
Command with ‘/‘

### ISSUE THREAD

**Issue by hanhphucnhat** [kroimon/Arduino-SerialCommand#17]
I want to add command “pumb/pumb1” 
This is work?
Thanks

**Comment by RayyanTahir** [comment]
Hi, if I understand you correctly, you want a command named pumb and argument pumb1 with separator '/'. If so go to SerialCommand.cpp and change line number 36 from:
`strcpy(delim, " ");`
to
`strcpy(delim, "/");`

I hope this helps.
